apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      name: flask-app
  template:
    metadata:
      labels:
        name: flask-app
    spec:
      containers:
      - name: flask-container
        image: ${USER_ID}.dkr.ecr.us-east-1.amazonaws.com/flask_app:${BUILD_NUMBER}
        resources:
        envFrom:
        - configMapRef:
            name: app-config-map
