
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app_volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pv-claim
  namespace: ingress-nginx
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi